start_date: "2026-01-26"
podcasts:
  - id: fsmi
    name: "FSMI Feed"
    rss_url: "https://feeds.megaphone.fm/FSMI7575968096"
  - id: lennys_podcast
    name: "Lenny's Podcast"
    rss_url: "https://api.substack.com/feed/podcast/10845.rss"
  - id: lennys_podcast_s198869
    name: "Lenny's Podcast (s/198869)"
    rss_url: "https://api.substack.com/feed/podcast/10845/s/198869.rss"
  - id: libsyn_121729
    name: "Libsyn 121729"
    rss_url: "https://rss.libsyn.com/shows/121729/destinations/713489.xml"
